services:
  element-app:
    image: docker.io/nfrastack/element
    container_name: element-app
    labels:
      - traefik.enable=true
      - traefik.http.routers.element.rule=Host(`element.example.com`)
      - traefik.http.services.element.loadbalancer.server.port=80
    volumes:
      - ./logs:/logs
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=element-app
      - SETUP_TYPE=AUTO

      # Single domain (default config.json)
      - HOME_SERVER_URL=https://matrix.example.com
      - BRAND=Element

      # Multi-domain
      # DOMAIN01_HOST=element.example1.com
      # DOMAIN01_URL=https://element.example1.com
      # DOMAIN01_BRAND=One
      # DOMAIN01_SERVER_NAME=example1.com
      # DOMAIN02_HOST=element.example2.com
      # DOMAIN02_URL=https://element.example2.com
      # DOMAIN02_BRAND=Two
      # DOMAIN02_SERVER_NAME=example2.com
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
